import { msg } from "@lingui/core/macro";
import { CustomMentionsField } from "../../../components/ui/settings/CustomMentionsField";
import { IgnoreListField } from "../../../components/ui/settings/IgnoreListField";
import settingsRegistry from "../registry";
import type { SettingDefinition } from "../types";

/**
 * Profile Settings
 */
const profileSettings: SettingDefinition[] = [
  {
    id: "profile.nickname",
    key: "nickname",
    category: "profile",
    subcategory: "Identity",
    title: msg`Nickname`,
    description: msg`Your unique identifier on this server`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Enter nickname...`,
    searchKeywords: ["nick", "username", "name", "identity"],
    priority: 1,
    validation: {
      required: true,
      maxLength: 30,
      pattern: /^[a-zA-Z0-9_\-[\]{}\\`|^]+$/,
    },
  },
  {
    id: "profile.displayName",
    key: "displayName",
    category: "profile",
    subcategory: "Identity",
    title: msg`Display Name`,
    description: msg`Your preferred display name`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Enter display name`,
    searchKeywords: ["display", "name", "visible"],
    priority: 2,
  },
  {
    id: "profile.realname",
    key: "realname",
    category: "profile",
    subcategory: "Identity",
    title: msg`Real Name`,
    description: msg`Your real or full name`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Enter real name`,
    searchKeywords: ["real", "name", "whois"],
    priority: 3,
  },
  {
    id: "profile.avatar",
    key: "avatar",
    category: "profile",
    subcategory: "Appearance",
    title: msg`Avatar`,
    description: msg`URL to your avatar image`,
    type: "text",
    defaultValue: "",
    placeholder: msg`https://example.com/avatar.png`,
    searchKeywords: ["avatar", "picture", "image", "photo"],
    priority: 4,
    validation: {
      pattern: /^(https?:\/\/)?.*\.(jpg|jpeg|png|gif|webp)$/i,
    },
  },
  {
    id: "profile.homepage",
    key: "homepage",
    category: "profile",
    subcategory: "Social",
    title: msg`Homepage`,
    description: msg`Your personal website`,
    type: "text",
    defaultValue: "",
    placeholder: msg`https://example.com`,
    searchKeywords: ["website", "url", "homepage", "social"],
    priority: 5,
  },
  {
    id: "profile.status",
    key: "status",
    category: "profile",
    subcategory: "Social",
    title: msg`Status`,
    description: msg`Your status message`,
    type: "text",
    defaultValue: "",
    placeholder: msg`What are you up to?`,
    searchKeywords: ["status", "message", "away"],
    priority: 6,
  },
  {
    id: "profile.pronouns",
    key: "pronouns",
    category: "profile",
    subcategory: "Identity",
    title: msg`Pronouns`,
    description: msg`Your pronouns, shown in your profile`,
    type: "text",
    defaultValue: "",
    placeholder: msg`she/her`,
    searchKeywords: ["pronouns", "gender", "they", "she", "he"],
    priority: 7,
  },
  {
    id: "profile.color",
    key: "color",
    category: "profile",
    subcategory: "Appearance",
    title: msg`Color`,
    description: msg`Your preferred color code`,
    type: "color",
    defaultValue: "#5865F2",
    searchKeywords: ["color", "theme", "appearance"],
    priority: 7,
  },
  {
    id: "profile.bot",
    key: "bot",
    category: "profile",
    subcategory: "Identity",
    title: msg`Bot`,
    description: msg`Mark as bot - usually 'on' or empty`,
    type: "text",
    defaultValue: "",
    placeholder: msg`on`,
    searchKeywords: ["bot", "automated", "robot"],
    priority: 8,
  },
  {
    id: "profile.awayMessage",
    key: "awayMessage",
    category: "profile",
    subcategory: "Status Messages",
    title: msg`Away Message`,
    description: msg`Default message when marking yourself as away`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Away from keyboard`,
    searchKeywords: ["away", "status", "message", "afk"],
    priority: 9,
  },
  {
    id: "profile.quitMessage",
    key: "quitMessage",
    category: "profile",
    subcategory: "Status Messages",
    title: msg`Quit Message`,
    description: msg`Message shown when you disconnect from the server`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Obby - Bringing IRC to the future`,
    searchKeywords: ["quit", "disconnect", "message", "leave"],
    priority: 10,
  },
];

/**
 * Notification Settings
 */
const notificationSettings: SettingDefinition[] = [
  {
    id: "notifications.enableSounds",
    key: "enableNotificationSounds",
    category: "notifications",
    subcategory: "Audio",
    title: msg`Enable Notification Sounds`,
    description: msg`Play sounds for mentions and messages`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["sound", "audio", "notification", "alert"],
    priority: 1,
  },
  {
    id: "notifications.soundFile",
    key: "notificationSound",
    category: "notifications",
    subcategory: "Audio",
    title: msg`Notification Sound`,
    description: msg`Custom notification sound file`,
    type: "file",
    defaultValue: "",
    accept: "audio/*",
    searchKeywords: ["sound", "file", "audio", "custom"],
    priority: 2,
    dependencies: [
      {
        settingId: "notifications.enableSounds",
        condition: (value) => value === true,
      },
    ],
  },
  {
    id: "notifications.enableHighlights",
    key: "enableHighlights",
    category: "notifications",
    subcategory: "Mentions",
    title: msg`Enable Highlights`,
    description: msg`Highlight messages that mention you`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["highlight", "mention", "ping"],
    priority: 3,
  },
  {
    id: "notifications.customMentions",
    key: "customMentions",
    category: "notifications",
    subcategory: "Mentions",
    title: msg`Custom Mentions`,
    description: msg`Additional words or phrases to highlight`,
    type: "custom",
    defaultValue: [],
    searchKeywords: ["custom", "mention", "highlight", "keyword"],
    priority: 4,
    customComponent: CustomMentionsField,
  },
];

/**
 * Preference Settings
 */
const preferenceSettings: SettingDefinition[] = [
  {
    id: "preferences.sendTyping",
    key: "sendTypingNotifications",
    category: "preferences",
    subcategory: "Chat",
    title: msg`Send Typing Notifications`,
    description: msg`Let others know when you are typing`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["typing", "notification", "indicator"],
    priority: 1,
  },
  {
    id: "preferences.markdown",
    key: "enableMarkdownRendering",
    category: "preferences",
    subcategory: "Chat",
    title: msg`Enable Markdown`,
    description: msg`Render markdown formatting in messages`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["markdown", "formatting", "rich text"],
    priority: 2,
  },
  {
    id: "preferences.showEvents",
    key: "showEvents",
    category: "preferences",
    subcategory: "Events",
    title: msg`Show All Events`,
    description: msg`Display all server events in chat`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["events", "messages", "activity"],
    priority: 3,
  },
  {
    id: "preferences.showNickChanges",
    key: "showNickChanges",
    category: "preferences",
    subcategory: "Events",
    title: msg`Show Nick Changes`,
    description: msg`Display when users change their nickname`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["nick", "change", "rename"],
    priority: 4,
    dependencies: [
      {
        settingId: "preferences.showEvents",
        condition: (value) => value === true,
      },
    ],
  },
  {
    id: "preferences.showJoinsParts",
    key: "showJoinsParts",
    category: "preferences",
    subcategory: "Events",
    title: msg`Show Joins/Parts`,
    description: msg`Display when users join or leave channels`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["join", "part", "leave", "enter"],
    priority: 5,
    dependencies: [
      {
        settingId: "preferences.showEvents",
        condition: (value) => value === true,
      },
    ],
  },
  {
    id: "preferences.showQuits",
    key: "showQuits",
    category: "preferences",
    subcategory: "Events",
    title: msg`Show Quits`,
    description: msg`Display when users disconnect from server`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["quit", "disconnect", "leave"],
    priority: 6,
    dependencies: [
      {
        settingId: "preferences.showEvents",
        condition: (value) => value === true,
      },
    ],
  },
  {
    id: "preferences.showKicks",
    key: "showKicks",
    category: "preferences",
    subcategory: "Events",
    title: msg`Show Kicks`,
    description: msg`Display when users are kicked from channels`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["kick", "ban", "remove"],
    priority: 7,
    dependencies: [
      {
        settingId: "preferences.showEvents",
        condition: (value) => value === true,
      },
    ],
  },
  {
    id: "preferences.multilineInput",
    key: "enableMultilineInput",
    category: "preferences",
    subcategory: "Input",
    title: msg`Enable Multiline Input`,
    description: msg`Allow entering multiple lines of text`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["multiline", "input", "text", "enter"],
    priority: 8,
  },
  {
    id: "preferences.multilineShiftEnter",
    key: "multilineOnShiftEnter",
    category: "preferences",
    subcategory: "Input",
    title: msg`Multiline on Shift+Enter`,
    description: msg`Use Shift+Enter for new lines (Enter sends)`,
    type: "toggle",
    defaultValue: true,
    searchKeywords: ["shift", "enter", "multiline", "keyboard"],
    priority: 9,
    dependencies: [
      {
        settingId: "preferences.multilineInput",
        condition: (value) => value === true,
      },
    ],
  },
  {
    id: "preferences.autoFallback",
    key: "autoFallbackToSingleLine",
    category: "preferences",
    subcategory: "Input",
    title: msg`Auto Fallback to Single Line`,
    description: msg`Automatically switch to single line for short messages`,
    type: "toggle",
    defaultValue: false,
    searchKeywords: ["fallback", "single", "line", "auto"],
    priority: 10,
    dependencies: [
      {
        settingId: "preferences.multilineInput",
        condition: (value) => value === true,
      },
    ],
  },
  {
    id: "preferences.ignoreList",
    key: "ignoreList",
    category: "preferences",
    subcategory: "Privacy",
    title: msg`Ignore List`,
    description: msg`Users and patterns to ignore`,
    type: "custom",
    defaultValue: [],
    searchKeywords: ["ignore", "block", "mute", "filter"],
    priority: 11,
    customComponent: IgnoreListField,
  },
];

/**
 * Media Settings
 * The slider UI is rendered as a custom branch in UserSettings ("media" category),
 * so this entry exists only to make the setting discoverable via search.
 */
const mediaSettings: SettingDefinition[] = [
  {
    id: "media.visibilityLevel",
    key: "mediaVisibilityLevel",
    category: "media",
    subcategory: "Display",
    title: msg`Media Previews`,
    description: msg`Control how much external media is loaded. Off / Safe / Trusted Sources / All Content.`,
    type: "toggle",
    defaultValue: 1,
    searchKeywords: [
      "media",
      "images",
      "safe",
      "trusted",
      "youtube",
      "vimeo",
      "soundcloud",
      "embed",
      "preview",
      "external",
      "content",
    ],
    priority: 1,
  },
];

/**
 * Account Settings (Hosted Chat Mode)
 */
const accountSettings: SettingDefinition[] = [
  {
    id: "account.nickname",
    key: "accountNickname",
    category: "account",
    subcategory: "Credentials",
    title: msg`Default Nickname`,
    description: msg`Your default nickname for all servers`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Enter default nickname...`,
    searchKeywords: ["nick", "default", "account"],
    priority: 1,
  },
  {
    id: "account.name",
    key: "accountName",
    category: "account",
    subcategory: "Credentials",
    title: msg`Account Name`,
    description: msg`Your account username for authentication`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Enter account name...`,
    searchKeywords: ["account", "login", "username", "auth"],
    priority: 2,
  },
  {
    id: "account.password",
    key: "accountPassword",
    category: "account",
    subcategory: "Credentials",
    title: msg`Account Password`,
    description: msg`Your account password for authentication`,
    type: "text", // Should be 'password' type when we add it
    defaultValue: "",
    placeholder: msg`Enter password...`,
    searchKeywords: ["password", "auth", "login"],
    priority: 3,
  },
  {
    id: "account.operName",
    key: "operUsername",
    category: "account",
    subcategory: "Operator",
    title: msg`Oper Username`,
    description: msg`IRC operator username`,
    type: "text",
    defaultValue: "",
    placeholder: msg`Enter oper username...`,
    searchKeywords: ["oper", "operator", "admin"],
    priority: 4,
  },
  {
    id: "account.operPassword",
    key: "operPassword",
    category: "account",
    subcategory: "Operator",
    title: msg`Oper Password`,
    description: msg`IRC operator password`,
    type: "text", // Should be 'password' type when we add it
    defaultValue: "",
    placeholder: msg`Enter oper password...`,
    searchKeywords: ["oper", "operator", "password", "admin"],
    priority: 5,
  },
  {
    id: "account.operOnConnect",
    key: "operOnConnect",
    category: "account",
    subcategory: "Operator",
    title: msg`Oper on Connect`,
    description: msg`Automatically authenticate as operator on connect`,
    type: "toggle",
    defaultValue: false,
    searchKeywords: ["oper", "auto", "connect", "operator"],
    priority: 6,
    dependencies: [
      {
        settingId: "account.operName",
        condition: (value) => !!value,
      },
      {
        settingId: "account.operPassword",
        condition: (value) => !!value,
      },
    ],
  },
];

/**
 * Register all settings
 */
export const registerAllSettings = () => {
  // Register all settings with the registry
  settingsRegistry.registerMany([
    ...profileSettings,
    ...notificationSettings,
    ...preferenceSettings,
    ...mediaSettings,
    ...accountSettings,
  ]);
};

// Export individual categories for use in components
export {
  accountSettings,
  mediaSettings,
  notificationSettings,
  preferenceSettings,
  profileSettings,
};

// Initialize settings on module load
registerAllSettings();

export default settingsRegistry;
