# https://hello.obby.world

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Build
        run: npm install && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./dist
          external_repository: obsidianirc/obsidianirc.github.io
          publish_branch: main
          cname: hello.obby.world
